# Generated by Django 3.0.5 on 2020-04-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('w1', models.CharField(max_length=200)),
                ('f1', models.IntegerField(default=0)),
                ('w2', models.CharField(max_length=200)),
                ('f2', models.IntegerField(default=0)),
                ('w3', models.CharField(max_length=200)),
                ('f3', models.IntegerField(default=0)),
                ('w4', models.CharField(max_length=200)),
                ('f4', models.IntegerField(default=0)),
                ('w5', models.CharField(max_length=200)),
                ('f5', models.IntegerField(default=0)),
                ('w6', models.CharField(max_length=200)),
                ('f6', models.IntegerField(default=0)),
                ('w7', models.CharField(max_length=200)),
                ('f7', models.IntegerField(default=0)),
                ('w8', models.CharField(max_length=200)),
                ('f8', models.IntegerField(default=0)),
                ('w9', models.CharField(max_length=200)),
                ('f9', models.IntegerField(default=0)),
                ('w91', models.CharField(max_length=200)),
                ('f91', models.IntegerField(default=0)),
            ],
        ),
    ]
